---
- hosts: windows
  tasks:
    - name: Download required Packages
      win_oneget:
        name: "xPSDesiredStateConfiguration"
      tags:
        - Oneget

    - name: Make sure the LCM refresh mode is disabled
      win_lcm5:
        refresh_mode: "Disabled"
      tags:
        - Config
